import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DemandWork.AI',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico' 
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="fixed top-0 left-0 right-0 z-50 backdrop-blur-2xl bg-white/30 dark:bg-black/30 border-b border-gray-300 dark:border-neutral-800">
          <div className="flex justify-between items-center px-6 py-4 max-w-5xl mx-auto">
            <Link 
              href="/" 
              className="text-xl font-bold text-black dark:text-white hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
            >
              <Image
                className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70]"
                src="/DW.svg"
                alt="DW Logo"
                width={60}
                height={50}
                priority
              />
            </Link>
            <div className="space-x-4">
              <Link 
                href="/login" 
                className="px-4 py-2 rounded-lg text-sm font-medium text-black dark:text-white hover:bg-gray-100/50 dark:hover:bg-gray-800/50 transition-colors"
              >
                Login
              </Link>
              <Link 
                href="/signup" 
                className="px-4 py-2 rounded-lg text-sm font-medium bg-black text-white dark:bg-white dark:text-black hover:bg-gray-800 dark:hover:bg-gray-200 transition-colors"
              >
                Sign Up
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}